import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'

import { Stick_No_Bills } from "next/font/google";

export const stickNoBills = Stick_No_Bills({
  subsets: ["latin"],
  weight: ["800"], // ExtraBold
  variable: "--font-stick",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Stick No Bills loaded:", stickNoBills.className, stickNoBills.variable);

  return (
    <html lang="en"
      className={`${stickNoBills.className}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
